# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#         - name: backend
#           image: 991499/instagram-backend:latest
#           ports:
#             - containerPort: 5000
#           env:
#             - name: PORT
#               value: "5000"
#             - name: ACCESS_TOKEN_EXPIRY
#               valueFrom:
#                 secretKeyRef:
#                   name: backend-secrets
#                   key: ACCESS_TOKEN_EXPIRY
#             - name: ACCESS_TOKEN_SECRET
#               valueFrom:
#                 secretKeyRef:
#                   name: backend-secrets
#                   key: ACCESS_TOKEN_SECRET
#             - name: CLOUDINARY_API_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: backend-secrets
#                   key: CLOUDINARY_API_KEY
#             - name: CLOUDINARY_API_SECRET
#               valueFrom:
#                 secretKeyRef:
#                   name: backend-secrets
#                   key: CLOUDINARY_API_SECRET
#             - name: CLOUDINARY_CLOUD_NAME
#               valueFrom:
#                 secretKeyRef:
#                   name: backend-secrets
#                   key: CLOUDINARY_CLOUD_NAME
#             - name: MONGODB_URI
#               valueFrom:
#                 secretKeyRef:
#                   name: backend-secrets
#                   key: MONGODB_URI
#             - name: REFRESH_TOKEN_EXPIRY
#               valueFrom:
#                 secretKeyRef:
#                   name: backend-secrets
#                   key: REFRESH_TOKEN_EXPIRY
#             - name: REFRESH_TOKEN_SECRET
#               valueFrom:
#                 secretKeyRef:
#                   name: backend-secrets
#                   key: REFRESH_TOKEN_SECRET
#           resources:
#             requests:
#               cpu: "200m"
#               memory: "256Mi"
#             limits:
#               cpu: "1"
#               memory: "512Mi"
