# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-config
# data:
#   prometheus.yml: |
#     global:
#       scrape_interval: 5s
#     scrape_configs:
#       - job_name: 'kubernetes-pods'
#         kubernetes_sd_configs:
#         - role: pod
