name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check AWS CLI Version
        run: aws --version

      - name: Print Environment Variables
        run: |
          echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
          echo "EKS_CLUSTER_NAME: ${{ secrets.AWS_CLUSTER_NAME}}
