name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check AWS CLI Version
        run: aws --version

      - name: Print Environment Variables
        run: |
          echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
          echo "EKS_CLUSTER_NAME: insta-clone-cluster"

      - name: Update K8s Manifests and Deploy
        run: |
          aws eks update-kubeconfig --region us-east-1 --name insta-clone-cluster --debug
          kubectl apply -f backend/backend-deployment.yaml
          kubectl apply -f backend/backend-service.yaml
          kubectl apply -f frontend/frontend-deployment.yaml
          kubectl apply -f frontend/frontend-service.yaml
          kubectl rollout restart deployment backend
          kubectl rollout restart deployment frontend
